static std::array<std::string, 235> builtin_functions = {
    "-A",               \
    "abs",              \
    "accept",           \
    "alarm",            \
    "atan2",            \
    "AUTOLOAD",         \
    "-b",               \
    "-B",               \
    "BEGIN",            \
    "bind",             \
    "binmode",          \
    "bless",            \
    "break",            \
    "-c",               \
    "-C",               \
    "caller",           \
    "chdir",            \
    "CHECK",            \
    "chmod",            \
    "chomp",            \
    "chop",             \
    "chown",            \
    "chr",              \
    "chroot",           \
    "close",            \
    "closedir",         \
    "connect",          \
    "cos",              \
    "crypt",            \
    "-d",               \
    "dbmclose",         \
    "dbmopen",          \
    "defined",          \
    "delete",           \
    "DESTROY",          \
    "die",              \
    "dump",             \
    "-e",               \
    "each",             \
    "END",              \
    "endgrent",         \
    "endhostent",       \
    "endnetent",        \
    "endprotoent",      \
    "endpwent",         \
    "endservent",       \
    "eof",              \
    "eval",             \
    "exec",             \
    "exists",           \
    "exit",             \
    "-f",               \
    "fcntl",            \
    "fileno",           \
    "flock",            \
    "fork",             \
    "format",           \
    "formline",         \
    "-g",               \
    "getc",             \
    "getgrent",         \
    "getgrgid",         \
    "getgrnam",         \
    "gethostbyaddr",    \
    "gethostbyname",    \
    "gethostent",       \
    "getlogin",         \
    "getnetbyaddr",     \
    "getnetbyname",     \
    "getnetent",        \
    "getpeername",      \
    "getpgrp",          \
    "getppid",          \
    "getpriority",      \
    "getprotobyname",   \
    "getprotobynumber", \
    "getprotoent",      \
    "getpwent",         \
    "getpwnam",         \
    "getpwuid",         \
    "getservbyname",    \
    "getservbyport",    \
    "getservent",       \
    "getsockname",      \
    "getsockopt",       \
    "glob",             \
    "gmtime",           \
    "goto",             \
    "grep",             \
    "hex",              \
    "index",            \
    "INIT",             \
    "int",              \
    "ioctl",            \
    "join",             \
    "-k",               \
    "keys",             \
    "kill",             \
    "-l",               \
    "last",             \
    "lc",               \
    "lcfirst",          \
    "length",           \
    "link",             \
    "listen",           \
    "local",            \
    "localtime",        \
    "log",              \
    "lstat",            \
    "-M",               \
    "map",              \
    "mkdir",            \
    "msgctl",           \
    "msgget",           \
    "msgrcv",           \
    "msgsnd",           \
    "my",               \
    "next",             \
    "not",              \
    "-o",               \
    "-O",               \
    "oct",              \
    "open",             \
    "opendir",          \
    "ord",              \
    "our",              \
    "-p",               \
    "pack",             \
    "pipe",             \
    "pop",              \
    "pos",              \
    "print",            \
    "printf",           \
    "prototype",        \
    "push",             \
    "quotemeta",        \
    "-r",               \
    "-R",               \
    "rand",             \
    "read",             \
    "readdir",          \
    "readline",         \
    "readlink",         \
    "readpipe",         \
    "recv",             \
    "redo",             \
    "ref",              \
    "rename",           \
    "require",          \
    "reset",            \
    "return",           \
    "reverse",          \
    "rewinddir",        \
    "rindex",           \
    "rmdir",            \
    "-s",               \
    "-S",               \
    "say",              \
    "scalar",           \
    "seek",             \
    "seekdir",          \
    "select",           \
    "semctl",           \
    "semget",           \
    "semop",            \
    "send",             \
    "setgrent",         \
    "sethostent",       \
    "setnetent",        \
    "setpgrp",          \
    "setpriority",      \
    "setprotoent",      \
    "setpwent",         \
    "setservent",       \
    "setsockopt",       \
    "shift",            \
    "shmctl",           \
    "shmget",           \
    "shmread",          \
    "shmwrite",         \
    "shutdown",         \
    "sin",              \
    "sleep",            \
    "socket",           \
    "socketpair",       \
    "sort",             \
    "splice",           \
    "split",            \
    "sprintf",          \
    "sqrt",             \
    "srand",            \
    "stat",             \
    "state",            \
    "study",            \
    "substr",           \
    "symlink",          \
    "syscall",          \
    "sysopen",          \
    "sysread",          \
    "sysseek",          \
    "system",           \
    "syswrite",         \
    "-t",               \
    "-T",               \
    "tell",             \
    "telldir",          \
    "tie",              \
    "tied",             \
    "time",             \
    "times",            \
    "truncate",         \
    "-u",               \
    "uc",               \
    "ucfirst",          \
    "umask",            \
    "undef",            \
    "UNITCHECK",        \
    "unlink",           \
    "unpack",           \
    "unshift",          \
    "untie",            \
    "use",              \
    "utime",            \
    "values",           \
    "vec",              \
    "-w",               \
    "-W",               \
    "wait",             \
    "waitpid",          \
    "wantarray",        \
    "warn",             \
    "write",            \
    "-x",               \
    "-X",               \
    "-z",
};
// reached end-of-file.
