// File-Handles
static std::vector<std::string> perl_filehandles = {
    "ARGV",    \
    "STDERR",  \
    "STDOUT",  \
    "ARGVOUT", \
    "STDIN",
};

// Builtin-Functions
static std::vector<std::string> perl_functions = {
    "-A",               \
    "abs",              \
    "accept",           \
    "alarm",            \
    "atan2",            \
    "AUTOLOAD",         \
    "-b",               \
    "-B",               \
    "BEGIN",            \
    "bind",             \
    "binmode",          \
    "bless",            \
    "break",            \
    "-c",               \
    "-C",               \
    "caller",           \
    "chdir",            \
    "CHECK",            \
    "chmod",            \
    "chomp",            \
    "chop",             \
    "chown",            \
    "chr",              \
    "chroot",           \
    "close",            \
    "closedir",         \
    "connect",          \
    "cos",              \
    "crypt",            \
    "-d",               \
    "dbmclose",         \
    "dbmopen",          \
    "defined",          \
    "delete",           \
    "DESTROY",          \
    "die",              \
    "dump",             \
    "-e",               \
    "each",             \
    "END",              \
    "endgrent",         \
    "endhostent",       \
    "endnetent",        \
    "endprotoent",      \
    "endpwent",         \
    "endservent",       \
    "eof",              \
    "eval",             \
    "exec",             \
    "exists",           \
    "exit",             \
    "-f",               \
    "fcntl",            \
    "fileno",           \
    "flock",            \
    "fork",             \
    "format",           \
    "formline",         \
    "-g",               \
    "getc",             \
    "getgrent",         \
    "getgrgid",         \
    "getgrnam",         \
    "gethostbyaddr",    \
    "gethostbyname",    \
    "gethostent",       \
    "getlogin",         \
    "getnetbyaddr",     \
    "getnetbyname",     \
    "getnetent",        \
    "getpeername",      \
    "getpgrp",          \
    "getppid",          \
    "getpriority",      \
    "getprotobyname",   \
    "getprotobynumber", \
    "getprotoent",      \
    "getpwent",         \
    "getpwnam",         \
    "getpwuid",         \
    "getservbyname",    \
    "getservbyport",    \
    "getservent",       \
    "getsockname",      \
    "getsockopt",       \
    "glob",             \
    "gmtime",           \
    "goto",             \
    "grep",             \
    "hex",              \
    "index",            \
    "INIT",             \
    "int",              \
    "ioctl",            \
    "join",             \
    "-k",               \
    "keys",             \
    "kill",             \
    "-l",               \
    "last",             \
    "lc",               \
    "lcfirst",          \
    "length",           \
    "link",             \
    "listen",           \
    "local",            \
    "localtime",        \
    "log",              \
    "lstat",            \
    "-M",               \
    "map",              \
    "mkdir",            \
    "msgctl",           \
    "msgget",           \
    "msgrcv",           \
    "msgsnd",           \
    "my",               \
    "next",             \
    "not",              \
    "-o",               \
    "-O",               \
    "oct",              \
    "open",             \
    "opendir",          \
    "ord",              \
    "our",              \
    "-p",               \
    "pack",             \
    "pipe",             \
    "pop",              \
    "pos",              \
    "print",            \
    "printf",           \
    "prototype",        \
    "push",             \
    "quotemeta",        \
    "-r",               \
    "-R",               \
    "rand",             \
    "read",             \
    "readdir",          \
    "readline",         \
    "readlink",         \
    "readpipe",         \
    "recv",             \
    "redo",             \
    "ref",              \
    "rename",           \
    "require",          \
    "reset",            \
    "return",           \
    "reverse",          \
    "rewinddir",        \
    "rindex",           \
    "rmdir",            \
    "-s",               \
    "-S",               \
    "say",              \
    "scalar",           \
    "seek",             \
    "seekdir",          \
    "select",           \
    "semctl",           \
    "semget",           \
    "semop",            \
    "send",             \
    "setgrent",         \
    "sethostent",       \
    "setnetent",        \
    "setpgrp",          \
    "setpriority",      \
    "setprotoent",      \
    "setpwent",         \
    "setservent",       \
    "setsockopt",       \
    "shift",            \
    "shmctl",           \
    "shmget",           \
    "shmread",          \
    "shmwrite",         \
    "shutdown",         \
    "sin",              \
    "sleep",            \
    "socket",           \
    "socketpair",       \
    "sort",             \
    "splice",           \
    "split",            \
    "sprintf",          \
    "sqrt",             \
    "srand",            \
    "stat",             \
    "state",            \
    "study",            \
    "substr",           \
    "symlink",          \
    "syscall",          \
    "sysopen",          \
    "sysread",          \
    "sysseek",          \
    "system",           \
    "syswrite",         \
    "-t",               \
    "-T",               \
    "tell",             \
    "telldir",          \
    "tie",              \
    "tied",             \
    "time",             \
    "times",            \
    "truncate",         \
    "-u",               \
    "uc",               \
    "ucfirst",          \
    "umask",            \
    "undef",            \
    "UNITCHECK",        \
    "unlink",           \
    "unpack",           \
    "unshift",          \
    "untie",            \
    "use",              \
    "utime",            \
    "values",           \
    "vec",              \
    "-w",               \
    "-W",               \
    "wait",             \
    "waitpid",          \
    "wantarray",        \
    "warn",             \
    "write",            \
    "-x",               \
    "-X",               \
    "-z",
};

// Builtin-Syntax
static std::vector<std::string> perl_syntax = {
    "__DATA__",    \
    "else",        \
    "lock",        \
    "qw",          \
    "__END__",     \
    "elsif",       \
    "lt",          \
    "qx",          \
    "__FILE__",    \
    "eq",          \
    "m",           \
    "s",           \
    "__LINE__",    \
    "exp",         \
    "ne",          \
    "sub",         \
    "__PACKAGE__", \
    "for",         \
    "no",          \
    "tr",          \
    "and",         \
    "foreach",     \
    "or",          \
    "unless",      \
    "cmp",         \
    "ge",          \
    "package",     \
    "until",       \
    "continue",    \
    "gt",          \
    "q",           \
    "while",       \
    "CORE",        \
    "if",          \
    "qq",          \
    "xor",         \
    "do",          \
    "le",          \
    "qr",          \
    "y",
};

// Builtin-Variables.
static std::vector<std::string> perl_variables = {
    "$!",                            \
    "$^RE_TRIE_MAXBUF",              \
    "$LAST_REGEXP_CODE_RESULT",      \
    "$\"",                           \
    "$^S",                           \
    "$LIST_SEPARATOR",               \
    "$#",                            \
    "$^T",                           \
    "$MATCH",                        \
    "$$",                            \
    "$^TAINT",                       \
    "$MULTILINE_MATCHING",           \
    "$%",                            \
    "$^UNICODE",                     \
    "$NR",                           \
    "$&",                            \
    "$^UTF8LOCALE",                  \
    "$OFMT",                         \
    "$'",                            \
    "$^V",                           \
    "$OFS",                          \
    "$(",                            \
    "$^W",                           \
    "$ORS",                          \
    "$)",                            \
    "$^WARNING_BITS",                \
    "$OS_ERROR",                     \
    "$*",                            \
    "$^WIDE_SYSTEM_CALLS",           \
    "$OSNAME",                       \
    "$+",                            \
    "$^X",                           \
    "$OUTPUT_AUTO_FLUSH",            \
    "$,",                            \
    "$_",                            \
    "$OUTPUT_FIELD_SEPARATOR",       \
    "$-",                            \
    "$`",                            \
    "$OUTPUT_RECORD_SEPARATOR",      \
    "$.",                            \
    "$a",                            \
    "$PERL_VERSION",                 \
    "$/",                            \
    "$ACCUMULATOR",                  \
    "$PERLDB",                       \
    "$0",                            \
    "$ARG",                          \
    "$PID",                          \
    "$:",                            \
    "$ARGV",                         \
    "$POSTMATCH",                    \
    "$;",                            \
    "$b",                            \
    "$PREMATCH",                     \
    "$<",                            \
    "$BASETIME",                     \
    "$PROCESS_ID",                   \
    "$=",                            \
    "$CHILD_ERROR",                  \
    "$PROGRAM_NAME",                 \
    "$>",                            \
    "$COMPILING",                    \
    "$REAL_GROUP_ID",                \
    "$?",                            \
    "$DEBUGGING",                    \
    "$REAL_USER_ID",                 \
    "$@",                            \
    "$EFFECTIVE_GROUP_ID",           \
    "$RS",                           \
    "$[",                            \
    "$EFFECTIVE_USER_ID",            \
    "$SUBSCRIPT_SEPARATOR",          \
    "$\\",                           \
    "$EGID",                         \
    "$SUBSEP",                       \
    "$]",                            \
    "$ERRNO",                        \
    "$SYSTEM_FD_MAX",                \
    "$^",                            \
    "$EUID",                         \
    "$UID",                          \
    "$^A",                           \
    "$EVAL_ERROR",                   \
    "$WARNING",                      \
    "$^C",                           \
    "$EXCEPTIONS_BEING_CAUGHT",      \
    "$|",                            \
    "$^CHILD_ERROR_NATIVE",          \
    "$EXECUTABLE_NAME",              \
    "$~",                            \
    "$^D",                           \
    "$EXTENDED_OS_ERROR",            \
    "%!",                            \
    "$^E",                           \
    "$FORMAT_FORMFEED",              \
    "%^H",                           \
    "$^ENCODING",                    \
    "$FORMAT_LINE_BREAK_CHARACTERS", \
    "%%ENV",                         \
    "$^F",                           \
    "$FORMAT_LINES_LEFT",            \
    "%INC",                          \
    "$^H",                           \
    "$FORMAT_LINES_PER_PAGE",        \
    "%OVERLOAD",                     \
    "$^I",                           \
    "$FORMAT_NAME",                  \
    "%SIG",                          \
    "$^L",                           \
    "$FORMAT_PAGE_NUMBER",           \
    "@+",                            \
    "$^M",                           \
    "$FORMAT_TOP_NAME",              \
    "@-",                            \
    "$^N",                           \
    "$GID",                          \
    "@_",                            \
    "$^O",                           \
    "$INPLACE_EDIT",                 \
    "@ARGV",                         \
    "$^OPEN",                        \
    "$INPUT_LINE_NUMBER",            \
    "@INC",                          \
    "$^P",                           \
    "$INPUT_RECORD_SEPARATOR",       \
    "@LAST_MATCH_START",             \
    "$^R",                           \
    "$LAST_MATCH_END",               \
    "$^RE_DEBUG_FLAGS",              \
    "$LAST_PAREN_MATCH",
};
// end-of-file.
